In [2]:
import pandas as pd
import requests

In [33]:
responce = requests.get('http://www.omdbapi.com/?t=iron+man&apikey=d663c0ea&')

In [38]:
responce.json()

{'Title': 'Iron Man',
 'Year': '2008',
 'Rated': 'PG-13',
 'Released': '02 May 2008',
 'Runtime': '126 min',
 'Genre': 'Action, Adventure, Sci-Fi',
 'Director': 'Jon Favreau',
 'Writer': 'Mark Fergus, Hawk Ostby, Art Marcum',
 'Actors': 'Robert Downey Jr., Gwyneth Paltrow, Terrence Howard',
 'Plot': 'After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.',
 'Language': 'English, Persian, Urdu, Arabic, Kurdish, Hindi, Hungarian',
 'Country': 'United States, Canada',
 'Awards': 'Nominated for 2 Oscars. 24 wins & 73 nominations total',
 'Poster': 'https://m.media-amazon.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_QL75_UX380_CR0,0,380,562_.jpg',
 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '7.9/10'},
  {'Source': 'Rotten Tomatoes', 'Value': '94%'},
  {'Source': 'Metacritic', 'Value': '79/100'}],
 'Metascore': '79',
 'imdbRating': '7.9',
 'imdbVotes': '1,223,183',
 'imdbID': 'tt0371746',
 'Type': 'movie',
 'DVD': 'N/A',
 'BoxOffice': '$319,034,126',
 'Production': 'N/A',
 'Website': 'N/A',
 'Response': 'True'}

In [59]:
pd.DataFrame(responce.json())

,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Plot,...,Metascore,imdbRating,imdbVotes,imdbID,Type,DVD,BoxOffice,Production,Website,Response
0,Iron Man,2008,PG-13,02 May 2008,126 min,"Action, Adventure, Sci-Fi",Jon Favreau,"Mark Fergus, Hawk Ostby, Art Marcum","Robert Downey Jr., Gwyneth Paltrow, Terrence H...","After being held captive in an Afghan cave, bi...",...,79,7.9,"1,223,183",tt0371746,movie,N/A,"$319,034,126",N/A,N/A,True
1,Iron Man,2008,PG-13,02 May 2008,126 min,"Action, Adventure, Sci-Fi",Jon Favreau,"Mark Fergus, Hawk Ostby, Art Marcum","Robert Downey Jr., Gwyneth Paltrow, Terrence H...","After being held captive in an Afghan cave, bi...",...,79,7.9,"1,223,183",tt0371746,movie,N/A,"$319,034,126",N/A,N/A,True
2,Iron Man,2008,PG-13,02 May 2008,126 min,"Action, Adventure, Sci-Fi",Jon Favreau,"Mark Fergus, Hawk Ostby, Art Marcum","Robert Downey Jr., Gwyneth Paltrow, Terrence H...","After being held captive in an Afghan cave, bi...",...,79,7.9,"1,223,183",tt0371746,movie,N/A,"$319,034,126",N/A,N/A,True

In [61]:
df = pd.json_normalize(responce.json())

In [63]:
df

,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Plot,...,Metascore,imdbRating,imdbVotes,imdbID,Type,DVD,BoxOffice,Production,Website,Response
0,Iron Man,2008,PG-13,02 May 2008,126 min,"Action, Adventure, Sci-Fi",Jon Favreau,"Mark Fergus, Hawk Ostby, Art Marcum","Robert Downey Jr., Gwyneth Paltrow, Terrence H...","After being held captive in an Afghan cave, bi...",...,79,7.9,"1,223,183",tt0371746,movie,N/A,"$319,034,126",N/A,N/A,True

In [57]:
df["Ratings"][0]

[{'Source': 'Internet Movie Database', 'Value': '7.9/10'},
 {'Source': 'Rotten Tomatoes', 'Value': '94%'},
 {'Source': 'Metacritic', 'Value': '79/100'}]

# Pokemon

In [111]:
pokemon = requests.get('https://pokeapi.co/api/v2/pokemon?limit=2000')

In [112]:
df = pd.DataFrame(pokemon.json()['results'])
df.drop(columns=['url'], inplace=True)
df

                         name
0                   bulbasaur
1                     ivysaur
2                    venusaur
3                  charmander
4                  charmeleon
...                       ...
1345            glimmora-mega
1346     tatsugiri-curly-mega
1347    tatsugiri-droopy-mega
1348  tatsugiri-stretchy-mega
1349          baxcalibur-mega

[1350 rows x 1 columns]

## Trying to get name, weight and height of all pokemons

In [132]:
data = requests.get('https://pokeapi.co/api/v2/pokemon/1')
pd.DataFrame([data.json()])[['name', 'weight', 'height']]

        name  weight  height
0  bulbasaur      69       7

In [131]:
df = pd.DataFrame()
for i in range(1, 1351):
    data = requests.get(f"https://pokeapi.co/api/v2/pokemon/{i}")
    temp = pd.DataFrame([data.json()])[['name', 'weight', 'height']]
    df = pd.concat([df, temp], ignore_index=True)

df

ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))