In [1]:
import pandas as pd
import requests 
from bs4 import BeautifulSoup

In [2]:
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
webpage = requests.get('https://www.ambitionbox.com/list-of-companies?page=1', headers=headers)

In [3]:
soup = BeautifulSoup(webpage.text, 'lxml')

## Extracting the individual box of a company. So that we can have entire info of company in one box (name, ratings, jobs, etc)

In [4]:
company = soup.find_all('div', class_='companyCardWrapper')

In [5]:
len(company)

20

In [6]:
company[0]

<div class="companyCardWrapper" itemprop="itemListElement" itemscope="itemscope" itemtype="http://schema.org/ListItem"><meta content="1" itemprop="position"/> <meta content="TCS" itemprop="name"/> <meta content="Tata Consultancy Services" itemprop="alternateName"/> <meta content="https://www.ambitionbox.com/overview/tcs-overview" itemprop="url"/> <meta content="https://static.ambitionbox.com/alpha/company/photos/logos/tcs.jpg" itemprop="image"/> <div class="companyCardWrapper__primaryInformation"><div class="companyCardWrapper__companyLogo"><img alt="Tata Consultancy Services logo" height="50" loading="lazy" onerror="this.onerror=null;this.src='/static/icons/company-placeholder.svg';" src="https://static.ambitionbox.com/assets/v2/images/rs:fit:200:200:false:false/aHR0cHM6Ly9tZWRpYS5uYXVrcmkuY29tL21lZGlhL2FiY29tcGxvZ28vdGNzLW9yaWdpbmFsLmpwZw.webp" width="50"/></div> <div class="companyCardWrapper__metaInformation"><div class="companyCardWrapper__header"><div class="companyCardWrapper__companyPrimaryDetailsTopSection"><a class="companyCardWrapper__companyName"><h2 class="companyCardWrapper__companyName" title="TCS">
									TCS
								</h2></a> <!-- --></div> <button arialabel="Follow" class="companyCardWrapper__FollowCTA g-btn g-btn--text g-btn--md" data-testid="" title="Follow" type="button"><!-- --> <span class="g-btn__label g-btn__label--md g-btn__label--text g-btn__label--loader">Follow</span> <!-- --> <!-- --></button> <!-- --></div> <div class="companyCardWrapper__ratingWrapper"><div class="companyCardWrapper__companyRatingWrapper"><div class="companyCardWrapper__companyRating"><div class="rating_star_container" style="line-height:20px;"><svg fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg"><rect fill="#FFBA01" height="20" rx="4" width="20"></rect> <path d="M6.295 16L7.27 11.5632L4 8.57895L8.32 8.18421L10 4L11.68 8.18421L16 8.57895L12.73 11.5632L13.705 16L10 13.6474L6.295 16Z" fill="white"></path></svg> <div class="rating_text rating_text--md"><div style="height:auto;">
			3.3<!-- --></div></div></div></div> <span class="companyCardWrapper__companyRatingCount">
								(1.1L)
							</span></div> <span class="companyCardWrapper__interLinking">
							IT Services &amp; Consulting | Bengaluru +441 other locations
						</span> <!-- --> <div class="companyCardWrapper__ratingComparisonWrapper"><div><div class="companyCardWrapper__ratingHeader"><img alt="thumbsup logo" height="14px" src="https://static.ambitionbox.com/static/companyListing/ThumbsUp.svg" width="14px"/> <span class="companyCardWrapper__ratingHeader--high">Highly Rated For</span></div> <span class="companyCardWrapper__ratingValues">Job Security</span></div> <div><div class="companyCardWrapper__ratingHeader"><img alt="thumbsdown logo" height="14px" src="https://static.ambitionbox.com/static/companyListing/ThumbsDown.svg" width="14px"/> <span class="companyCardWrapper__ratingHeader--critical">Critically Rated For</span></div> <span class="companyCardWrapper__ratingValues">Promotions, Salary, Work Satisfaction</span></div></div></div> <div class="viewSalaryInsights"><div class="salaryInsightsText">To view salary insights</div> <div class="designationSelectionText">
							Select designation
						</div></div> <!-- --></div></div> <div class="companyCardWrapper__tertiaryInformation"><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/reviews/tcs-reviews" target="_blank"><span class="companyCardWrapper__ActionCount">1.1L</span> <span class="companyCardWrapper__ActionTitle">Reviews</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/salaries/tcs-salaries" target="_blank"><span class="companyCardWrapper__ActionCount">10.1L</span> <span class="companyCardWrapper__ActionTitle">Salaries</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/interviews/tcs-interview-questions" target="_blank"><span class="companyCardWrapper__ActionCount">11.8k</span> <span class="companyCardWrapper__ActionTitle">Interviews</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/jobs/tcs-jobs-cmp" target="_blank"><span class="companyCardWrapper__ActionCount">4.1k</span> <span class="companyCardWrapper__ActionTitle">Jobs</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/benefits/tcs-benefits" target="_blank"><span class="companyCardWrapper__ActionCount">10.6k</span> <span class="companyCardWrapper__ActionTitle">Benefits</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/photos/tcs-photos" target="_blank"><span class="companyCardWrapper__ActionCount">93</span> <span class="companyCardWrapper__ActionTitle">Photos</span></a></div></div>

## Extracting names

In [10]:
company[0].find_all('h2')

[<h2 class="companyCardWrapper__companyName" title="TCS">
 									TCS
 								</h2>]

In [15]:
names = []
for i in company:
    names.append(i.find('h2').text.strip())

In [16]:
names

['TCS',
 'Accenture',
 'Wipro',
 'Cognizant',
 'Capgemini',
 'HDFC Bank',
 'Infosys',
 'HCLTech',
 'ICICI Bank',
 'Tech Mahindra',
 'Genpact',
 'TP',
 'Jio',
 'Axis Bank',
 'Concentrix Corporation',
 'Amazon',
 'Reliance Retail',
 'iEnergizer',
 'LTIMindtree',
 'IBM']

## Extracting ratings

In [21]:
company[0].find('div', class_='rating_text rating_text--md').text

'\n\t\t\t3.3'

In [24]:
ratings = []
for i in company:
    ratings.append(i.find('div', class_='rating_text rating_text--md').text.strip())

In [25]:
ratings

['3.3',
 '3.7',
 '3.6',
 '3.7',
 '3.6',
 '3.8',
 '3.5',
 '3.4',
 '4.0',
 '3.4',
 '3.6',
 '3.8',
 '4.4',
 '3.6',
 '3.6',
 '3.9',
 '3.9',
 '4.6',
 '3.6',
 '3.9']

## Extracting Type of company

In [32]:
company[0].find('span', class_='companyCardWrapper__interLinking').text.strip().split('|')[0].strip()

'IT Services & Consulting'

In [33]:
ctype = []
for i in company:
    ctype.append(i.find('span', class_='companyCardWrapper__interLinking').text.strip().split('|')[0].strip())

In [36]:
ctype

['IT Services & Consulting',
 'IT Services & Consulting',
 'IT Services & Consulting',
 'IT Services & Consulting',
 'IT Services & Consulting',
 'Banking',
 'IT Services & Consulting',
 'IT Services & Consulting',
 'Banking',
 'IT Services & Consulting',
 'Analytics & KPO',
 'BPO',
 'Telecom',
 'Banking',
 'BPO',
 'Internet',
 'Retail',
 'BPO',
 'IT Services & Consulting',
 'IT Services & Consulting']

## Extracting Highly rated for and critically rated for.

In [39]:
company[0].find_all('span', class_='companyCardWrapper__ratingValues')

[<span class="companyCardWrapper__ratingValues">Job Security</span>,
 <span class="companyCardWrapper__ratingValues">Promotions, Salary, Work Satisfaction</span>]

In [40]:
import numpy as np

In [41]:
highly_rated = []
critically_rated = []
for i in company:
    try:
        highly_rated.append(i.find_all('span', class_='companyCardWrapper__ratingValues')[0].text.strip())
    except:
        highly_rated.append(np.nan)
    try:
        critically_rated.append(i.find_all('span', class_='companyCardWrapper__ratingValues')[1].text.strip())
    except:
        critically_rated.append(np.nan)

In [44]:
len(highly_rated)

20

# Lets make df from these 20 company data

In [45]:
data_20 = {'name':names, 'rating':ratings, 'ctype':ctype, 'highly_rated':highly_rated, 'critically_rated':critically_rated}

In [46]:
df_20 = pd.DataFrame(data_20)

In [47]:
df_20

,name,rating,ctype,highly_rated,critically_rated
0,TCS,3.3,IT Services & Consulting,Job Security,"Promotions, Salary, Work Satisfaction"
1,Accenture,3.7,IT Services & Consulting,"Promotions, Salary, Work Satisfaction",NaN
2,Wipro,3.6,IT Services & Consulting,"Promotions, Salary, Work Satisfaction",NaN
3,Cognizant,3.7,IT Services & Consulting,"Promotions, Salary, Work Satisfaction",NaN
4,Capgemini,3.6,IT Services & Consulting,"Work Life Balance, Job Security","Promotions, Salary, Work Satisfaction"
5,HDFC Bank,3.8,Banking,"Job Security, Skill Development","Promotions, Salary"
6,Infosys,3.5,IT Services & Consulting,Job Security,"Promotions, Salary, Work Satisfaction"
7,HCLTech,3.4,IT Services & Consulting,"Promotions, Salary, Work Satisfaction",NaN
8,ICICI Bank,4.0,Banking,"Job Security, Promotions, Skill Development",NaN
9,Tech Mahindra,3.4,IT Services & Consulting,"Promotions, Salary, Work Satisfaction",NaN
10,Genpact,3.6,Analytics & KPO,Job Security,"Promotions, Salary, Work Satisfaction"
11,TP,3.8,BPO,"Work Life Balance, Job Security, Skill Develop...",NaN
12,Jio,4.4,Telecom,"Job Security, Skill Development, Company Culture",NaN
13,Axis Bank,3.6,Banking,"Promotions, Work Satisfaction, Company Culture",NaN
14,Concentrix Corporation,3.6,BPO,Job Security,"Promotions, Salary, Work Satisfaction"
15,Amazon,3.9,Internet,"Company Culture, Work Life Balance, Salary",Promotions
16,Reliance Retail,3.9,Retail,"Job Security, Skill Development, Work Life Bal...",Promotions
17,iEnergizer,4.6,BPO,"Salary, Company Culture, Work Life Balance",NaN
18,LTIMindtree,3.6,IT Services & Consulting,"Promotions, Salary, Work Satisfaction",NaN
19,IBM,3.9,IT Services & Consulting,"Work Life Balance, Company Culture, Job Security",Promotions

# Lets do for 500 pages.

In [52]:
final_df = pd.DataFrame()

for j in range(1, 501):
    url = 'https://www.ambitionbox.com/list-of-companies?page={}'.format(j)

    headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
    webpage = requests.get(url, headers=headers)

    soup = BeautifulSoup(webpage.text, 'lxml')

    company = soup.find_all('div', class_='companyCardWrapper')
    
    names = []
    ratings = []
    ctype = []
    highly_rated = []
    critically_rated = []
    for i in company:
        # Names
        names.append(i.find('h2').text.strip())
        
        # ratings
        try:
            ratings.append(i.find('div', class_='rating_text rating_text--md').text.strip())
        except:
            ratings.append(np.nan)
        
        # company type
        try:
            ctype.append(i.find('span', class_='companyCardWrapper__interLinking').text.strip().split('|')[0].strip())
        except:
            ctype.append(np.nan)
        
        # Highly rated for
        try:
            highly_rated.append(i.find_all('span', class_='companyCardWrapper__ratingValues')[0].text.strip())
        except:
            highly_rated.append(np.nan)
        
        # Critically rated for
        try:
            critically_rated.append(i.find_all('span', class_='companyCardWrapper__ratingValues')[1].text.strip())
        except:
            critically_rated.append(np.nan)

    data_20 = {'name':names, 'rating':ratings, 'ctype':ctype, 'highly_rated':highly_rated, 'critically_rated':critically_rated}
    df_20 = pd.DataFrame(data_20)

    final_df = pd.concat([final_df, df_20], ignore_index=True)

In [61]:
final_df

,name,rating,ctype,highly_rated,critically_rated
0,TCS,3.3,IT Services & Consulting,Job Security,"Promotions, Salary, Work Satisfaction"
1,Accenture,3.7,IT Services & Consulting,"Promotions, Salary, Work Satisfaction",NaN
2,Wipro,3.6,IT Services & Consulting,"Promotions, Salary, Work Satisfaction",NaN
3,Cognizant,3.7,IT Services & Consulting,"Promotions, Salary, Work Satisfaction",NaN
4,Capgemini,3.6,IT Services & Consulting,"Work Life Balance, Job Security","Promotions, Salary, Work Satisfaction"
...,...,...,...,...,...
9995,BBD University,3.6,Financial Services,"Promotions, Salary, Work Satisfaction",NaN
9996,Dlecta Foods,3.8,Food Processing,Skill Development,"Company Culture, Promotions"
9997,Autocop India,3.6,Semiconductors,"Company Culture, Promotions, Skill Development",NaN
9998,Techwise Digital,4.6,IT Services & Consulting,"Company Culture, Work Life Balance, Work Satis...",NaN
9999,PACL India,3.2,Real Estate,"Work Satisfaction, Skill Development, Salary",NaN

In [62]:
final_df.to_csv('company.csv', index=False)